# Generated by Django 4.1.3 on 2022-11-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextComment',
            fields=[
                ('auto_incremental_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('creador', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=200, null=True)),
                ('date_creacion', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
